apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dothejob
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "@every 1m"
    - name: direction
      value: input
scopes:
  - dothejob
